export const ScreenNames = {
  HOME: "Home",
  OTP: "OTP",
  BOTTOM_TAB: "BottomTab",
  WELCOME_SCREEN: "WelcomeScreen",
  SIGN_UP: "SignUp",
  SIGN_IN: "SignIn",
  RESET_PASSWORD: "ResetPassword",
  FORGOT_PASSWORD: "ForgotPassword",
  SELECT_COUNTRY: "SelectCountry",
  SELECT_CATEGORY: "SelectCategory",
  MAP: "Map",
  PROFILE: "Profile",
  ADD_STORE: "AddStore",
  HANDLE_STORE: "HandleStore",
  VERIFY_EMAIL: "VerifyEmail",
  MANAGE_POSTS: "ManagePosts",
};
