export const ScreenNames = {
  HOME: "Home",
  OTP: "OTP",
  BOTTOM_TAB: "BottomTab",
  WELCOME_SCREEN: "WelcomeScreen",
  SIGN_UP: "SignUp",
  SIGN_IN: "SignIn",
  RESET_PASSWORD: "ResetPassword",
  FORGOT_PASSWORD: "ForgotPassword",
  SELECT_COUNTRY: "SelectCountry",
  SELECT_CATEGORY: "SelectCategory",
  MAP: "MAP",
  FAVORITE: "Favorite",
  PROFILE: "Profile",
  PROFILE_SHOPPER: "ProfileShopper",
  PROFILE_MERCHANT: "ProfileMerchant",
  SETTINGS: "Settings",
};
